### ISSUE TITLE
Module Failure encountered when using openshift_process

### ISSUE THREAD

**Issue by radioactive73** [ansible-collections/community.okd#86]
SUMMARY
When using openshift_process a MODULE FAILURE error is encountered.

ISSUE TYPE
- Bug Report

COMPONENT NAME
Ansible module community.okd.openshift_process 1.1.2

ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dmorrissette/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

CONFIGURATION
```
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['~/repos/ansible/scripts/ansible-list-hosts.py']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/.vault_pass.txt
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = ignore
```

OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.3 (Ootpa)
Python 3.6.8

STEPS TO REPRODUCE
The following task definition is failing for me, I tried replacing the vars too just in case. The okd.k8s module seems fine so far.

```
- name: Process migrator template
  community.okd.openshift_process:
    api_key: "{{ capps_deploy_token }}"
    host: "{{ ocp_host }}"
    name: migrator-template
    namespace: "{{ capps_project }}"
    parameters:
      VERSION: "{{ capps_deploy_version }}"
    state: rendered
    validate_certs: no
```

EXPECTED RESULTS
To process the template or respond with a configuration error instead of a module failure error.

ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1620167971.6559699-404515-124202413047542/AnsiballZ_openshift_process.py", line 102, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1620167971.6559699-404515-124202413047542/AnsiballZ_openshift_process.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1620167971.6559699-404515-124202413047542/AnsiballZ_openshift_process.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.okd.plugins.modules.openshift_process', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.okd.openshift_process_payload_jrzkt864/ansible_community.okd.openshift_process_payload.zip/ansible_collections/community/okd/plugins/modules/openshift_process.py", line 389, in <module>
  File "/tmp/ansible_community.okd.openshift_process_payload_jrzkt864/ansible_community.okd.openshift_process_payload.zip/ansible_collections/community/okd/plugins/modules/openshift_process.py", line 385, in main
  File "/tmp/ansible_community.okd.openshift_process_payload_jrzkt864/ansible_community.okd.openshift_process_payload.zip/ansible_collections/community/okd/plugins/modules/openshift_process.py", line 334, in execute_module
KeyError: 'message'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1620167971.6559699-404515-124202413047542/AnsiballZ_openshift_process.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1620167971.6559699-404515-124202413047542/AnsiballZ_openshift_process.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1620167971.6559699-404515-124202413047542/AnsiballZ_openshift_process.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.okd.plugins.modules.openshift_process', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.okd.openshift_process_payload_jrzkt864/ansible_community.okd.openshift_process_payload.zip/ansible_collections/community/okd/plugins/modules/openshift_process.py\", line 389, in <module>\n  File \"/tmp/ansible_community.okd.openshift_process_payload_jrzkt864/ansible_community.okd.openshift_process_payload.zip/ansible_collections/community/okd/plugins/modules/openshift_process.py\", line 385, in main\n  File \"/tmp/ansible_community.okd.openshift_process_payload_jrzkt864/ansible_community.okd.openshift_process_payload.zip/ansible_collections/community/okd/plugins/modules/openshift_process.py\", line 334, in execute_module\nKeyError: 'message'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by abikouo** [comment]
@radioactive73 Thanks for taking the time to report this issue.
The issue was related to template definition which does not include a ``message`` attribute.
Could you please try using the PR attached here? 
@goetzrieger

**Comment by radioactive73** [comment]
@abikouo It's working now and I was able to register the result and apply it. Thanks!
Do you want me to close this issue or do you have a process (reference PR, etc)?

**Comment by gravesm** [comment]
@radioactive73 It will autoclose once the PR gets merged. Thanks for reporting and testing.

**Comment by goetzrieger** [comment]
Just tested the PR, works for me as well. Nice, thanks!
